------------------------------------------------
05-06-2020 21:42:37Ошибка в функции info_handler
------------------------------------------------
08-06-2020 22:43:29Ошибка в функции list index out of range
------------------------------------------------
08-06-2020 22:43:29Ошибка в функции table Users has 16 columns but 17 values were supplied
------------------------------------------------
08-06-2020 22:46:01Ошибка в функции list index out of range
------------------------------------------------
08-06-2020 22:47:44Ошибка в функции no such column: from_who
------------------------------------------------
08-06-2020 22:53:11Ошибка в функции list index out of range
------------------------------------------------
08-06-2020 22:54:00Ошибка в функции list index out of range
------------------------------------------------
08-06-2020 22:54:00Ошибка в функции list index out of range
------------------------------------------------
08-06-2020 22:54:00Ошибка в функции list index out of range
------------------------------------------------
08-06-2020 22:54:00Ошибка в функции list index out of range
------------------------------------------------
08-06-2020 22:54:00Ошибка в функции list index out of range
------------------------------------------------
08-06-2020 22:54:00Ошибка в функции list index out of range
------------------------------------------------
08-06-2020 22:54:00Ошибка в функции list index out of range
------------------------------------------------
08-06-2020 22:54:28Ошибка в функции list index out of range
------------------------------------------------
08-06-2020 22:55:00Ошибка в функции list index out of range
------------------------------------------------
08-06-2020 22:59:49Ошибка в функции list index out of range
------------------------------------------------
08-06-2020 23:00:23Ошибка в функции list index out of range
------------------------------------------------
08-06-2020 23:01:27Ошибка в функции list index out of range
------------------------------------------------
08-06-2020 23:03:15Ошибка в функции ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
------------------------------------------------
10-06-2020 19:38:41Ошибка в функции abort() takes no arguments (1 given)
------------------------------------------------
10-06-2020 20:16:30Ошибка в функции change_owner() missing 1 required positional argument: 'user_id'
------------------------------------------------
10-06-2020 20:19:22Ошибка в функции invalid literal for int() with base 10: 'owner558357692'
------------------------------------------------
10-06-2020 20:21:58Ошибка в функции list index out of range
------------------------------------------------
10-06-2020 20:21:59Ошибка в функции list index out of range
------------------------------------------------
10-06-2020 20:26:24Ошибка в функции list index out of range
------------------------------------------------
10-06-2020 20:59:59Ошибка в функции list index out of range
------------------------------------------------
10-06-2020 20:59:59Ошибка в функции list index out of range
------------------------------------------------
10-06-2020 20:59:59Ошибка в функции A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
[b'{"ok":false,"error_code":400,"description":"Bad Request: message text is empty"}']